language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'

stages:
  - Travis
  - name: 'Deploy'
    if: branch = master AND type = push

jobs:
  include:
    - stage: 'Test'
      name: 'Conventional Commits'
      script: commitlint-travis
    - name: 'Test'
      script: yarn test

    - stage: 'Deploy'
      script: yarn semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
